### ISSUE TITLE
Having Autobooga with oobabot enabled just results in oobabot failing

### ISSUE THREAD

**Issue by Mage-Enderman** [sammyf/Autobooga#8]
"WARNING An empty response was received from Oobabooga. Please check that the AI is running properly on the Oobabooga server at ws://localhost:5005."

I'd like to give my bot the ability to search the internet

**Comment by sammyf** [comment]
from the error it seems like the API isn't running, and if that's the case I don't think the problem is with Autobooga. Got any error or message in the console?

**Comment by Mage-Enderman** [comment]
https://hastebin.skyra.pw/levetuduvu.wren
Here's the errors I get

**Comment by sammyf** [comment]
hmm ... and if you disable Autobooga everything works? From the error message it seems like there are multiple exceptions happening, but none that are linked to my extension.

**Comment by jmoney7823956789378** [comment]
This is an issue with the way the context is handled in Autobooga vs what is returned to oobabot via the api. Oobabot sends the prompt+context+input and expects a single response as a reply. With Autobooga, the search results are appended directly to the output as context, rather than "output", and the api is returned nothing as a result (oobabooga believes the conversation to be completed already).

**Comment by sammyf** [comment]
Actually, the results are either prepended to the user prompt and then sent back for processing  (line 353 of script.py) I don't change the context at all.

**Comment by jmoney7823956789378** [comment]
> Actually, the results are prepended to the user prompt and then sent back for processing (line 353 of script.py) I don't change the context at all.

I gotcha, my bad. context is technically just prompt history anyways, and this may be more complicated than I thought. I'll look at it some more this week if I can.

**Comment by sammyf** [comment]
I'll push a new version by the way, which removes the ability of he LLM to autonomously ask for internet searches, as this is definitely broken. Sending the LLM into a search loop because the original answer to an unrelated question contained "search for" in it happens just way too often. So this might either make my extension useless for you, or maybe fix your problem (porque not los dos ;).

**Comment by Mage-Enderman** [comment]
Alright after updating Autobooga and oobaboogas text webui with Autobooga and oobabot enabled
Autobooga works fine in the webui but doesn't at all over Discord (afaik)
and the discord bot responds twice to any message sent to it

**Comment by jmoney7823956789378** [comment]
> Alright after updating Autobooga and oobaboogas text webui with Autobooga and oobabot enabled
> Autobooga works fine in the webui but doesn't at all over Discord (afaik)
> and the discord bot responds twice to any message sent to it

Yep, have found the same issue so I had to stop using it :(
May function better with a "less interactive" discord bot, or one that responds to single messages only.

**Comment by sammyf** [comment]
I'm kind of discontinuing Autobooga at this point, as trying to get help with the (ever changing, ever broken) Oobabooga extension support by asking simple questions results in being banned from the Subreddit and discord Server by the dev. I might fork Oobabooga's Text-Generation-WebUI and resume working on that particular extension but it won't be for TGW. 

You're welcome to fork the extension and improve it though :)
